default_language_version:
  python: python3.10
exclude: (docs/conf\.py)|(code_data/_test_minimized/.*)|(scripts/.*)
ci:
  skip: [pip-compile]
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.9.0
    hooks:
      - id: pip-compile
        files: ^(pyproject\.toml|requirements\.txt)$
        args:
          [
            --annotation-style=line,
            "--extra=test,docs,dev,rich",
            --allow-unsafe,
            pyproject.toml,
          ]
      - id: pip-compile
        files: ^(pyproject\.toml|requirements\.docs\.txt)$
        args:
          [
            --annotation-style=line,
            "--extra=docs,rich",
            --allow-unsafe,
            --output-file=requirements.docs.txt,
            pyproject.toml,
          ]
      - id: pip-compile
        files: ^(pyproject\.toml|requirements\.test\.txt)$
        args:
          [
            --annotation-style=line,
            --extra=test,
            --allow-unsafe,
            --output-file=requirements.test.txt,
            pyproject.toml,
          ]
