default_language_version:
  python: python3.10
exclude: (docs/conf\.py)|(code_data/test_minimized/.*)

repos:
  - repo: https://github.com/executablebooks/jupyter-book
    rev: v0.12.1
    hooks:
      - id: jb-to-sphinx
        args: ["docs"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.8.0
    hooks:
      - id: pip-compile
        files: ^(pyproject\.toml|requirements\.txt)$
        args:
          [
            --annotation-style=line,
            "--extra=test,docs,dev",
            --allow-unsafe,
            pyproject.toml,
          ]
# TODO: #47 Add format toml precommit
