name: Release
on:
  workflow_dispatch:
    inputs:
      part:
        description: 'Version part to increment'
        required: true
        default: 'minor' 
        type: choice
        options:
        - major
        - minor
        - patch 

jobs:
  # 1. Run bumpversion (commits and tags)
  # 2. Build and publish with flit
  # 3. Push commits and tags
  release:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.name "github-actions[bot]"
      # Bot email address: https://github.com/orgs/community/discussions/26560
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bump2version flit         
      - run: bump2version ${{ github.event.inputs.part }}
      - run: git push
      - run: git push --tags
      - run: flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}